
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/users_db
      REDIS_HOST: redis
  streamlit:
    build:
      context: .
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8501:8501"
    depends_on:
      - app
    environment:
      REDIS_HOST: redis
      DATABASE_URL: postgresql://user:password@db:5432/users_db
volumes:
  pg_data:
